# Exemple A du TP1 - Analyse Numerique

In [17]:
# importer la bibliotheque numy afin de faciliter la manipulation des  vecteurs et des matrices et beneficier de l'auto-completion

In [18]:
import numpy as  np 

In [19]:
# Definir un vecteur X et une matrice A

In [20]:
X = np.array([-4,0,3])
print (X)

[-4  0  3]


In [21]:
A = np.array([[2,3],[-1,1]])
print(A)


[[ 2  3]
 [-1  1]]


In [22]:
#Calculer la norme 1 - version automatique
norme1_X = np.linalg.norm(X,ord=1)
print (norme1_X)

7.0


In [23]:
norme1_A = np.linalg.norm(A,ord=1)
print (norme1_A)

4.0


In [24]:
# Calculer norme 2 

In [25]:
norme2_X = np.linalg.norm(X,ord=2)
print (norme2_X)

5.0


In [26]:
norme2_A = np.linalg.norm(A,ord=2)
print (norme2_A)

3.618033988749894


In [27]:
# Déterminer le conditionnement de  A 

In [28]:
invA = np.linalg.inv(A)
print (invA)


[[ 0.2 -0.6]
 [ 0.2  0.4]]


In [29]:
norme2_invA=np.linalg.norm(invA,ord=2)
print (norme2_invA)


0.7236067977499792


In [30]:
cond_A = norme2_A * norme2_invA
print(cond_A)


2.618033988749895


In [31]:
# Methode directe pour calculer le conditionnement

In [32]:
np.linalg.cond(A,p=2)


np.float64(2.6180339887498936)